# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: gluster-storage

# This parameter should be set to the name of an RSA keypair you have
# uplaoded to OpenStack.
cluster_keypair: default

# Site-specific network configuration.
cluster_net:
  - { net: "ilab", subnet: "ilab" }
  - { net: "p3-bdn", subnet: "p3-bdn" }
  - { net: "p3-lln", subnet: "p3-lln" }

# Use the 3 port node network resource.
cluster_environment_nodenet: "{{ role_path }}/files/environments/nodenet-3.yaml"

# Set config_drive to true so that ib0 interface is configured correctly
cluster_config_drive: true

# Multi-node application topology.  In this case we have a SLURM
# deployment formed from a login/controller node and a number of
# batch compute nodes.
cluster_groups:
  - "{{ storage_A }}"
  - "{{ storage_B }}"

storage_A:
  name: "A"
  flavor: "storage-A"
  image: "CentOS7.4-OpenHPC"
  num_nodes: 1
  user: "centos"

storage_B:
  name: "B"
  flavor: "storage-B"
  image: "CentOS7.4-OpenHPC"
  num_nodes: 2
  user: "centos"

cluster_roles: []

cluster_group_vars:
  cluster:
    gluster_cluster_volume_name: swarm_vol
    gluster_cluster_transport_interface: ib0
    gluster_cluster_transport_mode: rdma
    gluster_cluster_volume_options:
      cluster.nufa: 'on'
      performance.cache-size: '10GB'
  gluster-storage_A:
    gluster_cluster_block_devices:
      - sdb
      - sdc
      - sdd
      - sde
      - sdf
      - sdg
      - sdh
      - sdi
      - sdj
      - sdk
      - sdl
      - nvme0n1
      - nvme1n1
      - nvme2n1
      - nvme3n1
  gluster-storage_B:
    gluster_cluster_block_devices:
      - sdb
      - sdc
      - sdd
      - sde
      - sdf
      - sdg
      - sdh
      - sdi
      - sdj
      - sdk
      - sdl
      - sdm
      - sdn
      - sdo
      - sdp
      - sdq
      - sdr
      - sds
      - sdt
      - sdu
      - sdv
      - sdw
      - sdx
