#
# Copyright StackHPC, 2018
#
---
- hosts: cluster
  vars:
    ib_ipaddr: "{{ hostvars[inventory_hostname]['server_networks'][lln_name][0] }}"
  gather_facts: yes
  pre_tasks:
  - name: Enable passwordless sudo for wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'    
    become: yes
  roles:
  # Configure infiniband interface
  - configure_ib
  # Mount gluster volume on 
  - mount_glusterfs
  # Add cluster users
  - { role: singleplatform-eng.users, become: yes }

# Setup ceph mount
- import_playbook: manila-client.yml
...
