---
- name: Deploy glusterfs server
  hosts: cluster_glusterfs_server
  roles:
  - role: stackhpc.gluster-cluster

- name: Deploy glusterfs client
  hosts: cluster_glusterfs_client
  roles:
  - mount_glusterfs
...
